import { useEffect,useMemo,useState } from 'react'
import FounderCard from './FounderCard.jsx'
import FounderFilters from './FounderFilters.jsx'
import FounderIntentEditor from './FounderIntentEditor.jsx'
import FounderInviteModal from './FounderInviteModal.jsx'
import FounderProfile from './FounderProfile.jsx'
import FounderSprint from './FounderSprint.jsx'
import InvestorIntentPreview from './InvestorIntentPreview.jsx'
import { mockFounders } from '../data/mockFounders.js'
import { getFounderIntent,getFounderInvites,getSavedFounders,saveFounderIntent,saveFounderInvites,saveSavedFounders } from '../utils/founderStorage.js'

const defaultIntent={building:'AI-powered healthcare platform',stage:'Prototype',lookingFor:'Technical cofounder',domain:'Health-tech',commitment:'15+ hrs/week',location:'Sydney',risk:'Venture-scale',style:'Flexible',neededSkills:['Backend','Production ML']}
const initialFilters={domain:'',stage:'',commitment:'',capability:'',location:'',sort:'Most relevant'}
export default function FoundersPage(){
 const [intent,setIntent]=useState(()=>getFounderIntent(defaultIntent));const [filters,setFilters]=useState(initialFilters);const [saved,setSaved]=useState(getSavedFounders);const [invites,setInvites]=useState(getFounderInvites);const [profile,setProfile]=useState(null);const [inviteFounder,setInviteFounder]=useState(null);const [sprintFounder,setSprintFounder]=useState(null);const [notice,setNotice]=useState('')
 useEffect(()=>saveFounderIntent(intent),[intent]);useEffect(()=>saveSavedFounders(saved),[saved]);useEffect(()=>saveFounderInvites(invites),[invites])
 const scored=useMemo(()=>mockFounders.map((founder)=>{const complementary=founder.skills.filter((skill)=>intent.neededSkills.some((needed)=>skill.toLowerCase().includes(needed.toLowerCase())||needed.toLowerCase().includes(skill.toLowerCase()))).length;const domain=founder.domains.includes(intent.domain);const commitment=founder.commitment===intent.commitment;const score=Math.min(97,Math.round(founder.relevanceScore*.78+complementary*7+(domain?7:0)+(commitment?5:0)+(founder.location===intent.location?3:0)));return{founder,score,complementary}}),[intent])
 const options=useMemo(()=>({domain:[...new Set(mockFounders.flatMap((item)=>item.domains))].sort(),stage:[...new Set(mockFounders.map((item)=>item.startupStage))],commitment:[...new Set(mockFounders.map((item)=>item.commitment))],capability:[...new Set(mockFounders.flatMap((item)=>item.skills))].sort(),location:[...new Set(mockFounders.map((item)=>item.location))]}),[])
 const results=useMemo(()=>{const list=scored.filter(({founder})=>!filters.domain||founder.domains.includes(filters.domain)).filter(({founder})=>!filters.stage||founder.startupStage===filters.stage).filter(({founder})=>!filters.commitment||founder.commitment===filters.commitment).filter(({founder})=>!filters.capability||founder.skills.includes(filters.capability)).filter(({founder})=>!filters.location||founder.location===filters.location);if(filters.sort==='Complementary skills')return[...list].sort((a,b)=>b.complementary-a.complementary||b.score-a.score);if(filters.sort==='Commitment alignment')return[...list].sort((a,b)=>Number(b.founder.commitment===intent.commitment)-Number(a.founder.commitment===intent.commitment)||b.score-a.score);return[...list].sort((a,b)=>b.score-a.score)},[scored,filters,intent.commitment])
 const toggle=(setter,id)=>setter((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);const openInvite=(founder)=>setInviteFounder(founder);const sendInvite=(founder,message)=>{setInvites((current)=>current.some((item)=>item.founderId===founder.id)?current:[...current,{founderId:founder.id,message,sentAt:new Date().toISOString()}]);setInviteFounder(null);setProfile(null);setNotice('Exploration invite sent');setTimeout(()=>setNotice(''),3500)}
 return <div className="founders-page container"><header className="founders-header"><p className="eyebrow"><span /> FOUNDER NETWORK</p><h1>Find people worth <span>building with</span></h1><p>Explore founders and potential collaborators through complementary skills, commitment and shared direction.</p><strong>Explore first. Decide together.</strong></header><FounderIntentEditor intent={intent} onChange={setIntent}/><FounderFilters filters={filters} options={options} onChange={(key,value)=>setFilters((current)=>({...current,[key]:value}))} onReset={()=>setFilters(initialFilters)}/><div className="founder-results-heading"><div><p>PEOPLE TO EXPLORE</p><h2>{results.length} founder perspectives</h2></div><span>Intent relevance is indicative, never a compatibility guarantee.</span></div><div className="founder-grid">{results.map(({founder,score})=><FounderCard key={founder.id} founder={founder} score={score} saved={saved.includes(founder.id)} invited={invites.some((item)=>item.founderId===founder.id)} onExplore={()=>setProfile(founder)} onSave={()=>toggle(setSaved,founder.id)} onInvite={()=>openInvite(founder)}/>)}</div>{!results.length&&<div className="discover-empty"><h2>No founders match those filters yet</h2><p>Try another dimension. Exploring adjacent strengths can be useful.</p><button className="button" type="button" onClick={()=>setFilters(initialFilters)}>Reset filters</button></div>}<InvestorIntentPreview/>{notice&&<div className="invitation-toast" role="status">✓ {notice}</div>}{profile&&<FounderProfile founder={profile} userIntent={intent} onClose={()=>setProfile(null)} onInvite={()=>{openInvite(profile);setProfile(null)}} onSprint={()=>{setSprintFounder(profile);setProfile(null)}}/>} {inviteFounder&&<FounderInviteModal founder={inviteFounder} onClose={()=>setInviteFounder(null)} onSend={(message)=>sendInvite(inviteFounder,message)}/>} {sprintFounder&&<FounderSprint founder={sprintFounder} onClose={()=>setSprintFounder(null)}/>}</div>
}
